dir:
	gcc -Wall -o main findDir.c
	./main ../../ mtime + 10 -1
	./main ../../ mtime + 15 1
	./main ../../ mtime + 14  3
	

nftw:
	gcc -Wall -o main findNftw.c
	./main ../../ mtime + 7 -1
	./main ../../ mtime + 7 1
	./main ../../ atime - 5 2

